[package]
name = "Misti"
version = "0.0.0"
authors = ["ickdanny"]
categories = ["visualization"]
description = "A MIDI file visualizer."
edition = "2024"
keywords = ["midi"]
license = "MIT OR Apache-2.0"
homepage = "https://www.github.com/ickdanny/Misti"
repository = "https://www.github.com/ickdanny/Misti"
readme = "readme.md"

[dependencies]
midly = "0.5.3"
midir = "0.10.1"
nodi = { version = "1.0.3", features = ["midir"] }
