[package]
name = "Misti"
version = "0.0.0"
authors = ["ickdanny"]
categories = ["visualization"]
description = "A MIDI file visualizer."
edition = "2024"
keywords = ["midi"]
license = "MIT OR Apache-2.0"
homepage = "https://www.github.com/ickdanny/Misti"
repository = "https://www.github.com/ickdanny/Misti"
readme = "readme.md"
build = "build.rs"

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }

[dependencies]
bevy = { version = "0.19.1", default-features = false, features = ["2d", "dynamic_linking"] }
either = "1.18.0"
serde = "1.0.229"
toml = "1.1.6"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
