[package]
name = "Misti"
version = "0.0.0"
authors = ["ickdanny"]
categories = ["visualization"]
description = "A MIDI file visualizer."
edition = "2024"
keywords = ["midi"]
license = "MIT OR Apache-2.0"
homepage = "https://www.github.com/ickdanny/Misti"
repository = "https://www.github.com/ickdanny/Misti"
readme = "readme.md"
build = "build.rs"

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }